trigger:
 branches:
  exclude:
    - main  # Adjust the branch name as needed

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    # Install Terraform
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    sudo apt-get update && sudo apt-get install terraform
  displayName: 'Install Terraform'

- script: |
    # Terraform Init (Set up backend configuration)
    cd ./environments/dev/vm  # Adjust the path to your Terraform configuration
    terraform init -backend-config="storage_account_name=$(tfstate-storage-account)" -backend-config="container_name=$(tfstate-container)" -backend-config="key=$(tfstate-key)"
  displayName: 'Terraform Init'

- script: |
    # Terraform Plan
    cd ./environments/dev/vm
    terraform plan
  displayName: 'Terraform Plan'

- script: |
    # Terraform Apply (Auto-approve)
    cd ./environments/dev/vm
    terraform apply -auto-approve
  displayName: 'Terraform Apply'
