name: Terraform Azure Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_RESOURCE_GROUP_NAME: ${{ secrets.ARM_RESOURCE_GROUP_NAME }}
      ARM_STORAGE_ACCOUNT_NAME: ${{ secrets.ARM_STORAGE_ACCOUNT_NAME }}
      ARM_CONTAINER_NAME: ${{ secrets.ARM_CONTAINER_NAME }}
      ARM_KEY: ${{ secrets.ARM_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.7 # Use the version you want

    - name: Terraform Init
      working-directory: ./environments/dev/vm
      run: terraform init -backend-config=backend-config.tfvars

    - name: Terraform Plan
      working-directory: ./environments/dev/vm
      run: terraform plan

    - name: Terraform Apply
      working-directory: ./environments/dev/vm
      run: terraform apply -auto-approve
